- build.gradle.kts
- src/main/kotlin/Errors.kt
- src/main/kotlin/NewManifest.kt
- src/main/kotlin/data/InstallerManifestData.kt
- src/main/kotlin/data/SharedManifestData.kt
- src/main/kotlin/data/installer/Architecture.kt
- src/main/kotlin/data/installer/InstallerScope.kt
- src/main/kotlin/data/installer/InstallerType.kt
- src/main/kotlin/data/installer/UpgradeBehaviour.kt
- src/main/kotlin/data/msi/LCIDLibrary.kt
- src/main/kotlin/data/msi/Msi.kt
- src/main/kotlin/data/msi/MsiLibrary.kt
- src/main/kotlin/data/msi/ProductLanguage.kt
- src/main/kotlin/data/msi/SQLBuilder.kt
- src/main/kotlin/data/msix/Msix.kt
- src/main/kotlin/data/msix/MsixBundle.kt
- src/main/kotlin/data/shared/Locale.kt
- src/main/kotlin/data/shared/PackageIdentifier.kt
- src/main/kotlin/data/shared/Url.kt
- src/main/kotlin/data/zip/Zip.kt
- src/main/kotlin/schemas/InstallerManifest.kt
This also improves the safety of MSI reading and uses JNA to get the Locale Tag from an LCID (from an MSI).
> Add Zip support

- src/main/kotlin/data/GitHubImpl.kt
* Resolves https://github.com/vedantmgoyal2009/winget-releaser/issues/100
> feat: add environment variable to override fork owner

- build.gradle.kts
- libs.versions.toml
- src/main/kotlin/commands/QuickUpdate.kt
- src/main/kotlin/commands/RemoveVersion.kt
- src/main/kotlin/commands/token/Remove.kt
- src/main/kotlin/data/DefaultLocaleManifestData.kt
- src/main/kotlin/data/GitHubImpl.kt
- src/main/kotlin/data/InstallerManifestData.kt
- src/main/kotlin/data/installer/InstallerScope.kt
- src/main/kotlin/data/installer/UpgradeBehaviour.kt
- src/main/kotlin/data/locale/Description.kt
- src/main/kotlin/data/locale/License.kt
- src/main/kotlin/data/locale/PackageUrl.kt
- src/main/kotlin/data/locale/ReleaseNotesUrl.kt
- src/main/kotlin/data/locale/Tags.kt
- src/main/kotlin/data/shared/PackageIdentifier.kt
- src/main/kotlin/data/shared/PackageVersion.kt
- src/main/kotlin/data/shared/Publisher.kt
- src/main/kotlin/detection/github/GitHubDetection.kt
- src/main/kotlin/utils/MenuCreator.kt
- src/test/kotlin/VersionTests.kt
Added interactive menu:
- ~~Add an optional 'none' or 'no idea' option.~~ https://github.com/russellbanks/Komac/pull/111/commits/4b7c5070593157bbefb5c09b4a914e383f78a8f2
- remove unnecessary deferred on GitHub object
> feat: add interactive menus

- src/main/kotlin/data/InstallerManifestData.kt
- src/main/kotlin/input/FileWriter.kt
> feat: Create directory if it doesn't exist

- src/main/kotlin/detection/github/GitHubExtensions.kt
- src/test/kotlin/GitHubTests.kt
Noticed from https://github.com/microsoft/winget-pkgs/pull/97838
> fix: URLs with dash not getting converted to issue

- src/main/kotlin/data/GitHubImpl.kt
- src/main/kotlin/detection/github/GitHubExtensions.kt
- src/main/kotlin/utils/Hashing.kt
- src/test/kotlin/GitHubTests.kt
Before:
`- b858cb282617fb0956d960215c8e84d1ccf909c6 New feature`
After:
`- New feature`
> fix: remove sha1 from release notes

- src/main/kotlin/commands/QuickUpdate.kt
- src/main/kotlin/data/GitHubImpl.kt
- src/main/kotlin/data/InstallerManifestData.kt
- src/main/kotlin/utils/ManifestUtils.kt
> fix: update relative file path when using parameters

- src/main/kotlin/commands/QuickUpdate.kt
> Print URL after PR creation

- src/main/kotlin/commands/QuickUpdate.kt
- src/main/kotlin/data/shared/PackageIdentifier.kt
- src/main/kotlin/data/shared/PackageVersion.kt
- src/main/kotlin/data/shared/Url.kt
- src/main/kotlin/detection/ParameterUrls.kt
- src/main/kotlin/network/HttpUtils.kt
- src/main/kotlin/network/KtorGitHubConnector.kt
- src/test/kotlin/IdentifierTests.kt
- src/test/kotlin/VersionTests.kt
- src/test/kotlin/utils/GitHubUtilsTests.kt
Reverts to using the 1.1.0 matching algorithm to fix the issue outlined in https://github.com/vedantmgoyal2009/winget-releaser/issues/117.
> fix: url matching algorithm

- src/main/kotlin/commands/CommandUtils.kt
- src/main/kotlin/commands/QuickUpdate.kt
- src/main/kotlin/data/GitHubImpl.kt
- src/main/kotlin/detection/ParameterUrls.kt
This explicitly specifies exit code of 1 when there is an error
> fix: throw exit code 1 when there is an error

- build.gradle.kts
- src/main/kotlin/token/windows/CredAdvapi32.kt
- src/main/kotlin/token/windows/CredManagerBackedSecureStore.kt
Fixes https://github.com/vedantmgoyal2009/winget-releaser/issues/129
> fix: lateinit credential has not been initialised

- src/main/kotlin/utils/FileAnalyser.kt
- src/main/kotlin/utils/FileUtils.kt
- src/main/kotlin/utils/GitHubUtils.kt
> fix: exception when creating new package

- src/main/kotlin/data/GitHubImpl.kt
Related to https://github.com/vedantmgoyal2009/winget-releaser/issues/118#issuecomment-1483887908
> fix: only skip manifest if PR is open in CI

- src/main/kotlin/commands/QuickUpdate.kt
Resolves https://github.com/vedantmgoyal2009/winget-releaser/issues/141
> fix: non-default locales not being added on quick update

- src/main/kotlin/commands/Cleanup.kt
This iteration queries pull requests rather than commits.
> fix: cleanup command deleting open branches

- src/main/kotlin/github/GitHubDetection.kt
* https://github.com/vedantmgoyal2009/winget-releaser/issues/162
> Get Github repo's homepage if available

- src/main/kotlin/commands/QuickUpdate.kt
- src/main/kotlin/data/shared/InstallerUrl.kt
- src/main/kotlin/schemas/manifest/InstallerManifest.kt
- src/main/kotlin/utils/FileAnalyser.kt
- src/main/kotlin/utils/UrlUtils.kt
- src/main/kotlin/utils/UrlsToInstallerMatcher.kt
- src/main/kotlin/utils/Zip.kt
- src/main/kotlin/utils/msi/Msi.kt
- src/main/kotlin/utils/msix/Msix.kt
- src/test/kotlin/ParameterUrlTests.kt
- src/test/kotlin/TestUtils.kt
- src/test/kotlin/utils/UrlUtilTests.kt
- Resolves #243 
- Resolves #215
> Improve installer matching

- src/main/kotlin/Komac.kt
- src/main/kotlin/network/Proxy.kt
Resolves #247
```pwsh
komac --use-system-proxy [command]
```
> Add `--use-system-proxy` parameter

- src/main/kotlin/utils/jna/GObject.kt
- src/main/kotlin/utils/jna/JNAFunctionMapper.kt
- src/main/kotlin/utils/jna/LibMsi.kt
- src/main/kotlin/utils/jna/WinMsi.kt
- src/main/kotlin/utils/msi/Msi.kt
- src/main/kotlin/utils/msi/MsiArch.kt
- Resolves #254
- Resolves #250
- Addresses #110 
On Linux, Komac will now require [libmsi](https://wiki.gnome.org/msitools):
```bash
sudo apt install msitools
```
> Use LibMsi on Linux

- src/main/kotlin/utils/msi/Msi.kt
- src/main/kotlin/utils/msi/ProductLanguage.kt
> Use LibMsi on macOS

- src/main/kotlin/schemas/manifest/InstallerManifest.kt
- src/main/kotlin/utils/FileAnalyser.kt
- src/main/kotlin/utils/UrlUtils.kt
- src/main/kotlin/utils/Zip.kt
- src/main/kotlin/utils/msix/MsixBundle.kt
- src/test/kotlin/TestUtils.kt
- src/test/kotlin/utils/UrlUtilTests.kt
> Identify architecture at end of URL

- src/main/kotlin/data/InstallerManifestData.kt
- src/main/kotlin/schemas/SchemaType.kt
- src/main/kotlin/schemas/Schemas.kt
- src/main/kotlin/schemas/manifest/DefaultLocaleManifest.kt
- src/main/kotlin/schemas/manifest/InstallerManifest.kt
- src/main/kotlin/schemas/manifest/LocaleManifest.kt
- src/main/kotlin/schemas/manifest/VersionManifest.kt
> Support manifest version 1.5.0

- src/main/kotlin/github/ReleaseNotesFormatter.kt
- src/test/kotlin/extensions/StringExtensionsTest.kt
> Fix release notes going over max length

- src/main/kotlin/commands/CommandUtils.kt
- src/main/kotlin/commands/NewManifest.kt
- src/main/kotlin/commands/QuickUpdate.kt
- src/main/kotlin/commands/RemoveVersion.kt
- src/main/kotlin/commands/branch/Cleanup.kt
- src/main/kotlin/token/Token.kt
- src/main/kotlin/token/TokenStore.kt
> Check internet connection at start

- src/msi.rs
https://learn.microsoft.com/en-us/windows/win32/msi/template-summary
Resolves #471
> Detect Arm64 and Arm architectures from MSI

- src/commands/update_version.rs
- src/manifests/default_locale_manifest.rs
- src/manifests/locale_manifest.rs
Similar to WingetCreate's [`--release-notes-url`](https://github.com/microsoft/winget-create/blob/main/doc/update.md#arguments)
> Add `release-notes-url` update option

- src/commands/new_version.rs
- src/commands/update_version.rs
- src/commands/utils/mod.rs
Allows for existing PR check to be skipped in automated / CI environments.
> Add option to skip existing PR check

- .github/workflows/release.yml
See actions/runner-images#12947
> Pin release CI Windows version to 2022 for `iscc.exe`

- .github/workflows/release.yml
- README.md
See russellbanks/homebrew-tap#5
> Migrate Homebrew tap to homebrew-core

- src/installers/burn/manifest/package/install_condition.rs
Tested with the CrowdStrike Windows installer
Before:
```
Error:
0: invalid type: string "BrokenUpgradeVersionDetected <> 2", expected a borrowed string
```
After:
```yml
Architecture: x86
InstallerType: burn
Scope: machine
InstallerUrl: https://example.com/
InstallerSha256: '0000000000000000000000000000000000000000000000000000000000000000'
AppsAndFeaturesEntries:
- DisplayName: CrowdStrike Windows Sensor
Publisher: CrowdStrike, Inc.
DisplayVersion: 7.20.19011.0
ProductCode: '{ca89b9a9-9c8b-4aee-b83e-588106763730}'
UpgradeCode: '{3066BDCB-C39B-4D6C-9179-F4EC96B08D40}'
InstallerType: burn
```
> Add Burn NotEq operator (`<>`)

- src/installers/burn/manifest/package/install_condition.rs
Tested with OktaVerifySetup-6.1.1.0-1fa1c5e.exe
Falls back to `Eq` for non-string types, which seems to be implied by the existence of operators like `~>` (greater than, case insensitive). But I've only seen `~=` once, with strings in this installer.
Didn't send yesterday cause I didn't want merge conflicts, hope that's ok.
Before:
```
invalid type: string "VersionNT64 AND (SKU ~= \"ALL\" OR SKU ~= \"ODA\" OR OktaJoinDetected)", expected a borrowed string
```
After:
```yml
Architecture: x86
InstallerType: burn
Scope: machine
InstallerUrl: https://example.com/
InstallerSha256: '0000000000000000000000000000000000000000000000000000000000000000'
AppsAndFeaturesEntries:
- DisplayName: Okta Verify
Publisher: Okta, Inc.
DisplayVersion: 6.1.1.0
ProductCode: …
```
> Add Burn case-insensitive equality operator (`~=`)
